# Day 2 — Pandas & Export CSV

Goal: Load raw CSV into pandas, clean basics, and export clean_data.csv

## Setup
If you don't have the required packages, run in a terminal:
```bash
pip install pandas
```

In [35]:
import pandas as pd
from pathlib import Path

raw_path = Path('1-raw_data.csv')

df = pd.read_csv(raw_path, encoding='utf-8')
df['scraped_at'] = pd.to_datetime(df['scraped_at'])

print('Loaded rows:', len(df))
df.head()

Loaded rows: 567

,name,hash_name,wear,url,price_usd,quantity,scraped_at
0,AK-47 | Aphrodite (Battle-Scarred),AK-47 | Aphrodite (Battle-Scarred),Battle-Scarred,https://steamcommunity.com/market/listings/730...,16.46,700,2026-07-07 15:20:41.415129
1,AK-47 | Aphrodite (Factory New),AK-47 | Aphrodite (Factory New),Factory New,https://steamcommunity.com/market/listings/730...,668.21,55,2026-07-07 15:20:41.415187
2,AK-47 | Aphrodite (Field-Tested),AK-47 | Aphrodite (Field-Tested),Field-Tested,https://steamcommunity.com/market/listings/730...,25.59,785,2026-07-07 15:20:41.415236
3,AK-47 | Aphrodite (Minimal Wear),AK-47 | Aphrodite (Minimal Wear),Minimal Wear,https://steamcommunity.com/market/listings/730...,54.88,660,2026-07-07 15:20:41.415283
4,AK-47 | Aphrodite (Well-Worn),AK-47 | Aphrodite (Well-Worn),Well-Worn,https://steamcommunity.com/market/listings/730...,17.50,753,2026-07-07 15:20:41.415330

## Inspect the DataFrame
Run the checks below to see types and missing values.

In [36]:
print('shape:', df.shape)
print(df.info())
print('Missing values per column:')
print(df.isna().sum())

shape: (567, 7)
<class 'pandas.DataFrame'>
RangeIndex: 567 entries, 0 to 566
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        567 non-null    str
 1   hash_name   567 non-null    str
 2   wear        567 non-null    str
 3   url         567 non-null    str
 4   price_usd   567 non-null    float64
 5   quantity    567 non-null    int64
 6   scraped_at  567 non-null    datetime64[us]
dtypes: datetime64[us](1), float64(1), int64(1), str(4)
memory usage: 31.1 KB
None
Missing values per column:
name          0
hash_name     0
wear          0
url           0
price_usd     0
quantity      0
scraped_at    0
dtype: int64

## Cleaning steps
- Parse scraped_at to datetime
- Ensure price is numeric: use price if present, else try to parse price_text
- Fill missing quantity with 1 and convert to int
- Compute total = price * quantity
- Drop rows missing item or price

In [37]:
df['price_usd'] = pd.to_numeric(df['price_usd'], errors='coerce')

df['quantity'] = pd.to_numeric(df['quantity'], errors='coerce')
df['quantity'] = df['quantity'].fillna(0)
df['quantity'] = df['quantity'].astype(int)
df['total'] = df['price_usd'] * df['quantity'].astype(int)
df['total'] = df['total'].round(2)
 
before = len(df)
mask_has_name = df['name'].notna()
mask_has_price = df['price_usd'].notna()
df = df[mask_has_name & mask_has_price]
after = len(df)
print(f'{before - after} Zeilen entfernt wegen fehlendem Namen oder Preis')

df.head()

0 Zeilen entfernt wegen fehlendem Namen oder Preis

,name,hash_name,wear,url,price_usd,quantity,scraped_at,total
0,AK-47 | Aphrodite (Battle-Scarred),AK-47 | Aphrodite (Battle-Scarred),Battle-Scarred,https://steamcommunity.com/market/listings/730...,16.46,700,2026-07-07 15:20:41.415129,11522.00
1,AK-47 | Aphrodite (Factory New),AK-47 | Aphrodite (Factory New),Factory New,https://steamcommunity.com/market/listings/730...,668.21,55,2026-07-07 15:20:41.415187,36751.55
2,AK-47 | Aphrodite (Field-Tested),AK-47 | Aphrodite (Field-Tested),Field-Tested,https://steamcommunity.com/market/listings/730...,25.59,785,2026-07-07 15:20:41.415236,20088.15
3,AK-47 | Aphrodite (Minimal Wear),AK-47 | Aphrodite (Minimal Wear),Minimal Wear,https://steamcommunity.com/market/listings/730...,54.88,660,2026-07-07 15:20:41.415283,36220.80
4,AK-47 | Aphrodite (Well-Worn),AK-47 | Aphrodite (Well-Worn),Well-Worn,https://steamcommunity.com/market/listings/730...,17.50,753,2026-07-07 15:20:41.415330,13177.50

## Deduplicate and export CSV
Create a dedupe key (url + item + scraped_date) and drop duplicates before writing CSV.

In [38]:
df = df.drop_duplicates(subset=['hash_name'])

out_path = Path('clean_data.csv')
df.to_csv(out_path, index=False)
print('Wrote', len(df), 'rows to', out_path)

Wrote 567 rows to clean_data.csv