# Day 2 — Pandas & Export CSV

Goal: Load raw CSV into pandas, clean basics, and export clean_data.csv

## Setup
If you don't have the required packages, run in a terminal:
```bash
pip install pandas
```

In [1]:
import pandas as pd
from pathlib import Path

raw_path = Path('1-raw_data.csv')

df = pd.read_csv(raw_path, encoding='utf-8')
df['scraped_at'] = pd.to_datetime(df['scraped_at'])

print('Loaded rows:', len(df))
df.head()

Loaded rows: 571

,name,hash_name,wear,url,price_usd,quantity,scraped_at
0,AK-47 | Aphrodite (Battle-Scarred),AK-47 | Aphrodite (Battle-Scarred),Battle-Scarred,https://steamcommunity.com/market/listings/730...,16.50,724,2026-07-08 13:40:54.304979
1,AK-47 | Aphrodite (Factory New),AK-47 | Aphrodite (Factory New),Factory New,https://steamcommunity.com/market/listings/730...,620.00,54,2026-07-08 13:40:54.305039
2,AK-47 | Aphrodite (Field-Tested),AK-47 | Aphrodite (Field-Tested),Field-Tested,https://steamcommunity.com/market/listings/730...,24.67,805,2026-07-08 13:40:54.305092
3,AK-47 | Aphrodite (Minimal Wear),AK-47 | Aphrodite (Minimal Wear),Minimal Wear,https://steamcommunity.com/market/listings/730...,54.62,668,2026-07-08 13:40:54.305138
4,AK-47 | Aphrodite (Well-Worn),AK-47 | Aphrodite (Well-Worn),Well-Worn,https://steamcommunity.com/market/listings/730...,18.25,757,2026-07-08 13:40:54.305184

## Inspect the DataFrame
Run the checks below to see types and missing values.

In [2]:
print('shape:', df.shape)
print(df.info())
print('Missing values per column:')
print(df.isna().sum())

shape: (571, 7)
<class 'pandas.DataFrame'>
RangeIndex: 571 entries, 0 to 570
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        571 non-null    str
 1   hash_name   571 non-null    str
 2   wear        571 non-null    str
 3   url         571 non-null    str
 4   price_usd   571 non-null    float64
 5   quantity    571 non-null    int64
 6   scraped_at  571 non-null    datetime64[us]
dtypes: datetime64[us](1), float64(1), int64(1), str(4)
memory usage: 31.4 KB
None
Missing values per column:
name          0
hash_name     0
wear          0
url           0
price_usd     0
quantity      0
scraped_at    0
dtype: int64

## Cleaning steps
- Parse scraped_at to datetime
- Ensure price is numeric: use price if present, else try to parse price_text
- Fill missing quantity with 1 and convert to int
- Compute total = price * quantity
- Drop rows missing item or price

In [3]:
df['price_usd'] = pd.to_numeric(df['price_usd'], errors='coerce')

df['quantity'] = pd.to_numeric(df['quantity'], errors='coerce')
df['quantity'] = df['quantity'].fillna(0)
df['quantity'] = df['quantity'].astype(int)
df['total market value'] = df['price_usd'] * df['quantity'].astype(int)
df['total market value'] = df['total market value'].round(2)
 
before = len(df)
mask_has_name = df['name'].notna()
mask_has_price = df['price_usd'].notna()
df = df[mask_has_name & mask_has_price]
after = len(df)
print(f'{before - after} Zeilen entfernt wegen fehlendem Namen oder Preis')

df.head()

0 Zeilen entfernt wegen fehlendem Namen oder Preis

,name,hash_name,wear,url,price_usd,quantity,scraped_at,total market value
0,AK-47 | Aphrodite (Battle-Scarred),AK-47 | Aphrodite (Battle-Scarred),Battle-Scarred,https://steamcommunity.com/market/listings/730...,16.50,724,2026-07-08 13:40:54.304979,11946.00
1,AK-47 | Aphrodite (Factory New),AK-47 | Aphrodite (Factory New),Factory New,https://steamcommunity.com/market/listings/730...,620.00,54,2026-07-08 13:40:54.305039,33480.00
2,AK-47 | Aphrodite (Field-Tested),AK-47 | Aphrodite (Field-Tested),Field-Tested,https://steamcommunity.com/market/listings/730...,24.67,805,2026-07-08 13:40:54.305092,19859.35
3,AK-47 | Aphrodite (Minimal Wear),AK-47 | Aphrodite (Minimal Wear),Minimal Wear,https://steamcommunity.com/market/listings/730...,54.62,668,2026-07-08 13:40:54.305138,36486.16
4,AK-47 | Aphrodite (Well-Worn),AK-47 | Aphrodite (Well-Worn),Well-Worn,https://steamcommunity.com/market/listings/730...,18.25,757,2026-07-08 13:40:54.305184,13815.25

## Deduplicate and export CSV
Create a dedupe key (url + item + scraped_date) and drop duplicates before writing CSV.

In [4]:
df = df.drop_duplicates(subset=['hash_name'])

out_path = Path('clean_data.csv')
df.to_csv(out_path, index=False)
print('Wrote', len(df), 'rows to', out_path)

Wrote 571 rows to clean_data.csv